title: FS: >-
         This is my portfolio showcasing my projects and skills.
baseurl: ""
url: "https://FS1309931.github.io" 
theme: Dinky
layout: default
title: About Me
---

Hello! I am [FS].
My goals and objective is to pass all my classes and be a professional Goalkeeper in soccer. My life future goals is to be a goalokeeper with a family of 5 including me and having a nice beautiful house with 23 acres of land.
